#!/usr/bin/env bash

source $(dirname "$0")/../lib.sh

if [ ! -f $(dirname "$0")/../$CONFIG_FILE ]; then
	echo -e "${RED}Config file not found.${NC} run 'cp config.sample config' to create one"
	exit 0
fi

source $(dirname "$0")/../$CONFIG_FILE

SCRIPT_NAME=$(basename "$0")

if [ $# -ne 2 ]; then
	echo "$SCRIPT_NAME [sql file] [database name]"
	exit 1
fi

if [ ! -f $CREDENTIAL_PATH ]; then
	echo -e "${RED}Can not find the credential file${NC} ($CREDENTIAL_PATH)"
	exit 0
fi

if [ ! -f "$1" ]; then
	echo -e "${RED}Source file doesn't exist${NC} ($1)"
	exit 0
fi

RESULT=`mysql --defaults-file="$CREDENTIAL_PATH" -e "SHOW DATABASES;" | grep "^$2$"`

if [ "$RESULT" != "$2" ]; then
	echo -e "${GREEN}$2${NC} database created${NC}"
	mysql --defaults-file="$CREDENTIAL_PATH" -e "CREATE DATABASE $2 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
else
	echo -e "${RED}Database already exists${NC} ($2)"
	exit 0
fi

echo -e "Running SQL script (${GREEN}$1${NC}) to the database '${GREEN}$2${NC}'"
mysql --defaults-file="$CREDENTIAL_PATH" $2 < "$1"

echo "Done"
