#!/usr/bin/env bash

source $(dirname "$0")/../lib.sh

if [ ! -f $(dirname "$0")/../$CONFIG_FILE ]; then
    echo -e "${RED}Config file not found.${NC} run 'cp config.sample config' to create one"
    exit 0
fi

source $(dirname "$0")/../$CONFIG_FILE

# if the default network interface is not defined, get it from the first argument
if [ -z $INTERFACE ]; then
	if [ ! -z "$1" ]; then
		INTERFACE="eth1"
	else
		INTERFACE="$1"
	fi
fi

# getting environmental strings
unameOut="$(uname -s)"

VAGRANT_IP=$(eval "ifconfig $INTERFACE | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'")

if [ -z "$VAGRANT_IP" ]; then
	exit 0
fi

# if mailcatcher is already installed, start creating scripts
if [ -f "$BIN_PATH/mailcatcher" ]; then

	# register mailcatcher start up script in linux
	case "${unameOut}" in
		Linux*)

			echo -e "This script not necessary to run in Linux"
			;;
		Darwin*)
			$BIN_PATH/mailcatcher --ip=$VAGRANT_IP --smtp-port $SMTP_PORT --http-port $WEB_PORT
			;;
		*)
			;;
	esac

else
	echo -e "${RED}mailcatcher not installed${NC}"
    exit 0
fi

exit 1
